# Site title and subtitle. This is used in _includes/header.html
title: 'RaptorScript'
subtitle: ''

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/raptor-lang'

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: "/:categories/:title"

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

collections:
  ref:
    title: Reference
    output: true
    permalink: /ref/:path/
  docs:
    title: Documentation
    output: true
    permalink: /docs/:path/

defaults:
  - 
    values:
      layout: page
